# Generated by Django 3.2.4 on 2021-07-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('resposta1', models.IntegerField()),
                ('resposta2', models.CharField(max_length=20)),
                ('resposta3', models.CharField(max_length=20)),
                ('resposta4', models.CharField(max_length=20)),
                ('resposta5', models.CharField(max_length=20)),
                ('resposta6', models.IntegerField()),
                ('resposta7', models.CharField(max_length=20)),
                ('resposta8', models.CharField(max_length=20)),
                ('resposta9', models.IntegerField()),
                ('resposta10', models.IntegerField()),
                ('pontuacao', models.IntegerField()),
            ],
        ),
    ]
