# Generated by Django 3.2.4 on 2021-07-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='show',
            name='type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(max_length=900),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
