# Generated by Django 3.2.4 on 2021-07-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0002_auto_20210703_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='photo',
        ),
        migrations.AddField(
            model_name='castmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
