# Generated by Django 3.2.4 on 2021-07-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0002_alter_show_description'),
        ('tvcrib', '0003_auto_20210703_0524'),
    ]

    operations = [
    ]
