# Generated by Django 3.2.4 on 2021-07-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0005_auto_20210703_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cast_photos/'),
        ),
    ]
