# Generated by Django 3.2.4 on 2021-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0007_auto_20210703_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='cardCover',
            field=models.ImageField(blank=True, null=True, upload_to='image-db/08657dd9a3104ae3ba5a5932d401b93b'),
        ),
        migrations.AlterField(
            model_name='show',
            name='movieCover',
            field=models.ImageField(blank=True, null=True, upload_to='image-db/24480f018d554b89bd157d0910d9e585'),
        ),
    ]
