# Generated by Django 3.2.4 on 2021-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0009_auto_20210703_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='cardCover',
            field=models.ImageField(blank=True, null=True, upload_to='./63cf82c8fb524fc3ade88a87e8f5a031.jpg'),
        ),
        migrations.AlterField(
            model_name='show',
            name='movieCover',
            field=models.ImageField(blank=True, null=True, upload_to='./32d3059517f642e6a2d6d3a91180d6e9.jpg'),
        ),
    ]
