# Generated by Django 3.2.4 on 2021-07-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0012_alter_show_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='character',
            new_name='characters',
        ),
    ]
