# Generated by Django 3.2.4 on 2021-07-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0013_rename_character_show_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clareza', models.IntegerField()),
                ('rigor', models.IntegerField()),
                ('significancia', models.IntegerField()),
                ('originalidade', models.IntegerField()),
                ('logica', models.IntegerField()),
                ('precisao', models.IntegerField()),
                ('comentario', models.IntegerField()),
                ('classificacaoGlobal', models.IntegerField()),
            ],
        ),
    ]
