# Generated by Django 3.2.4 on 2021-07-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0014_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='classificacaoGlobal',
            field=models.TextField(max_length=500),
        ),
    ]
