# Generated by Django 3.2.4 on 2021-07-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0015_alter_comentario_classificacaoglobal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='classificacaoGlobal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(max_length=500),
        ),
    ]
