# Generated by Django 3.2.4 on 2021-07-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0017_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
