# Generated by Django 3.2.4 on 2021-07-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0018_delete_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cast_photos'),
        ),
    ]
