# Generated by Django 3.2.4 on 2021-07-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0019_alter_castmember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='get_actor_file_name'),
        ),
    ]
