# Generated by Django 3.2.4 on 2021-07-05 00:06

from django.db import migrations, models
import tvcrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('tvcrib', '0020_alter_castmember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=tvcrib.models.get_actor_file_name),
        ),
    ]
